---
# Users module for Calamares — HML Reimagined
defaultGroups:
  - name: users
    must_exist: false
    system: true
  - name: adm
    must_exist: false
    system: true
  - name: cdrom
    must_exist: false
    system: true
  - name: dip
    must_exist: false
    system: true
  - name: lpadmin
    must_exist: false
    system: true
  - name: plugdev
    must_exist: false
    system: true
  - name: sambashare
    must_exist: false
    system: true
  - name: sudo
    must_exist: false
    system: true

autologinGroup: autologin

doAutologin: false

setRootPassword: true
doReusePassword: true

passwordRequirements:
    nonempty: true
    minLength: 1
    maxLength: -1
    libpwquality: []

allowWeakPasswords: true
allowWeakPasswordsDefault: false

userShell: /bin/zsh
