---
# Welcome module configuration for Calamares
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true
showDonateUrl:          false

requirements:
    requiredStorage:    20.0
    requiredRam:        2.0
    internetCheckUrl:   http://connectivitycheck.ubuntu.com
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - storage
        - ram
        - root

geoIP:
    style:    "json"
    url:      "https://geoip.kde.org/v1/calamares"
    selector: ""
