[kdeglobals][General]
ColorScheme=HMLReimagined
widgetStyle=Breeze

[kdeglobals][Icons]
Theme=hml-icons

[kdeglobals][KDE]
LookAndFeelPackage=hml.reimagined
SingleClick=false
AnimationDurationFactor=0.5

[plasmarc][Theme]
name=hml

[kwinrc][org.kde.kdecoration2]
library=org.kde.breeze
theme=Breeze

[kwinrc][Compositing]
Backend=OpenGL
GLCore=true

[kcminputrc][Mouse]
cursorTheme=hml-cursors
cursorSize=24
